FROM ruby:2.6.6-alpine3.12

RUN gem install bundler && \
    apk add --no-cache --update build-base cmake git

RUN git clone https://github.com/exercism/ruby-test-runner /usr/src/ruby-test-runner && \
    cd /usr/src/ruby-test-runner && \
    bundle install

WORKDIR /usr/src/app

RUN gem install bundler:2.1.4
COPY Gemfile Gemfile.lock ./
RUN bundle install

ENTRYPOINT bundle update --full-index --conservative exercism_config && \
           EXERCISM_DOCKER=true EXERCISM_ENV=development bundle exec setup_exercism_config && \
           ./bin/worker
