#!/bin/bash
docker build -t exercism-tooling-invoker . -f ./Dockerfile.dev

PWD=$(PWD)
docker run --entrypoint "/bin/sh" \
    -e EXERCISM_DOCKER=true \
    --mount "type=bind,src=$PWD,dst=/usr/src/app" \
    --rm \
    -it exercism-tooling-invoker \
    '-c' 'bundle exec rake test'
